import { Router } from "express";

// Admin Routes
import adminAuthRoute from "./admin/v1/auth.route";
import adminUserRoute from "./admin/v1/user.route";
import adminPermissionRoute from "./admin/v1/permission.route";
import adminRoleRoute from "./admin/v1/role.route";
import adminMemberTypeRoute from "./admin/v1/member-type.route";
import adminMemberPlanRoute from "./admin/v1/member-plan.route";
import adminMemberRoute from "./admin/v1/member.route";
import adminProsRoute from "./admin/v1/pros.route";
import adminConsRoute from "./admin/v1/cons.route";
import adminShopLevelRoute from "./admin/v1/shop-level.route";
import adminShopRoute from "./admin/v1/shop.route";
import adminTagRoute from "./admin/v1/tag.route";
import adminPostRoute from "./admin/v1/post.route";
import adminWorkoutRoute from "./admin/v1/workout.route";
import adminBankInformationRoute from "./admin/v1/bank-information.route";
import adminPhysicalLimitationRoute from "./admin/v1/physical-limitation.route";
import adminPlaceRoute from "./admin/v1/place.route";
import adminDietTypeRoute from "./admin/v1/diet-type.route";
import adminBodyAttentionAreaRoute from "./admin/v1/body-attention-area.route";
import adminMealRoute from "./admin/v1/meal.route";
import adminBadHabitRoute from "./admin/v1/bad-habit.route";
import adminWaterTrackerRoute from "./admin/v1/water-tracker.route";
import adminMemberRequestRoute from "./admin/v1/member-request.route";
import adminPaymentRoute from "./admin/v1/payment.route";
import adminProficientLevelRoute from "./admin/v1/proficient-level.route";
import adminBodyGoalRoute from "./admin/v1/body-goal.route";
import adminShopLevelRequestRoute from "./admin/v1/shop-level-request.route";
import adminCategoryRoute from "./admin/v1/category.route";
import adminAttendanceRoute from "./admin/v1/attendance.route";
import adminReportCategoryRoute from "./admin/v1/report-category.route";

// Member Routes
import memberAuthRoute from "./member/v1/auth.route";
import memberProfileRoute from "./member/v1/profile.route";
import memberPostRoute from "./member/v1/post.route";
import memberSocialPostRoute from "./member/v1/member-social-post.route";
import memberPostCommentRoute from "./member/v1/post-comment.route";
import memberTagRoute from "./member/v1/tag.route";
import memberMemberTypeRoute from "./member/v1/member-type.route";
import memberPlanRoute from "./member/v1/member-plan.route";
import memberRequestRoute from "./member/v1/member-request.route";
import memberPaymentRoute from "./member/v1/payment.route";
import memberBankInformationRoute from "./member/v1/bank-information.route";
import memberShopRoute from "./member/v1/shop.route";
import memberShopPostRoute from "./member/v1/shop-post.route";
import memberShopPostCommentRoute from "./member/v1/shop-post-comment.route";
import memberShopPostReactionRoute from "./member/v1/shop-post-reaction.route";
import memberShopRatingRoute from "./member/v1/shop-rating.route";
import memberShopLevelRoute from "./member/v1/shop-level.route";
import memberWorkoutRoute from "./member/v1/workout.route";
import memberShopLevelRequestRoute from "./member/v1/shop-level-request.route";
import memberFriendRequestRoute from "./member/v1/friend-request.route";
import memberFriendRoute from "./member/v1/friend.route";
import memberPostReactionRoute from "./member/v1/post-reaction.route";
import memberConversationRoute from "./member/v1/conversation.route";
import memberMessageRoute from "./member/v1/message.route";
import memberMember from "./member/v1/member.route";
import memberBlockRoute from "./member/v1/block.route";
import memberMealRoute from "./member/v1/meal.route";
import memberMealTrackerRoute from "./member/v1/meal-tracker.route";
import memberWaterTrackerRoute from "./member/v1/water-tracker.route";
import systemParameterRoute from "./member/v1/system-parameter.route";
import memberReportCategoryRoute from "./member/v1/report-category.route";
import memberPostReportRoute from "./member/v1/post-report.route";
import memberPostViewsRoute from "./member/v1/post-views.route";
import planDurationRoute from "./member/v1/plan-duration.route";
import memberPlanListRoute from "./member/v1/member-plan-list.route";
import memberTypeLevelRoute from "./member/v1/member-type-level.route";

const router = Router();

// Admin Routes
router.use("/admin/v1/auth", adminAuthRoute);
router.use("/admin/v1/users", adminUserRoute);
router.use("/admin/v1/roles", adminRoleRoute);
router.use("/admin/v1/permissions", adminPermissionRoute);
router.use("/admin/v1/member-types", adminMemberTypeRoute);
router.use("/admin/v1/member-plans", adminMemberPlanRoute);
router.use("/admin/v1/members", adminMemberRoute);
router.use("/admin/v1/pros", adminProsRoute);
router.use("/admin/v1/cons", adminConsRoute);
router.use("/admin/v1/shop-levels", adminShopLevelRoute);
router.use("/admin/v1/shops", adminShopRoute);
router.use("/admin/v1/tags", adminTagRoute);
router.use("/admin/v1/posts", adminPostRoute);
router.use("/admin/v1/workouts", adminWorkoutRoute);
router.use("/admin/v1/bank-informations", adminBankInformationRoute);
router.use("/admin/v1/physical-limitations", adminPhysicalLimitationRoute);
router.use("/admin/v1/places", adminPlaceRoute);
router.use("/admin/v1/diet-types", adminDietTypeRoute);
router.use("/admin/v1/body-attention-areas", adminBodyAttentionAreaRoute);
router.use("/admin/v1/meals", adminMealRoute);
router.use("/admin/v1/bad-habits", adminBadHabitRoute);
router.use("/admin/v1/body-goals", adminBodyGoalRoute);
router.use("/admin/v1/proficient-levels", adminProficientLevelRoute);
router.use("/admin/v1/water-trackers", adminWaterTrackerRoute);
router.use("/admin/v1/member-requests", adminMemberRequestRoute);
router.use("/admin/v1/shop-level-requests", adminShopLevelRequestRoute);
router.use("/admin/v1/categories", adminCategoryRoute);
router.use("/admin/v1/payments", adminPaymentRoute);
router.use("/admin/v1/attendances", adminAttendanceRoute);
router.use("/admin/v1/report-category", adminReportCategoryRoute);


// Member Routes
router.use("/member/v1/auth", memberAuthRoute);
router.use("/member/v1/profile", memberProfileRoute);
router.use("/member/v1", memberSocialPostRoute);
router.use("/member/v1/posts", memberPostRoute);
router.use("/member/v1/post-comments", memberPostCommentRoute);
router.use("/member/v1/tags", memberTagRoute);
router.use("/member/v1/member-types", memberMemberTypeRoute);
router.use("/member/v1/member-plans", memberPlanRoute);
router.use("/member/v1/member-request", memberRequestRoute);
router.use("/member/v1/payment", memberPaymentRoute);
router.use("/member/v1/bank-informations", memberBankInformationRoute);
router.use("/member/v1/shop-levels", memberShopLevelRoute);
router.use("/member/v1/shops", memberShopRoute);
router.use("/member/v1/shop-posts", memberShopPostRoute);
router.use("/member/v1/shop-post-comments", memberShopPostCommentRoute);
router.use("/member/v1/shop-ratings", memberShopRatingRoute);
router.use("/member/v1/shop-post-reactions", memberShopPostReactionRoute);
router.use("/member/v1/shop-level-requests", memberShopLevelRequestRoute);
router.use("/member/v1/workouts", memberWorkoutRoute);
router.use("/member/v1/friend-requests", memberFriendRequestRoute);
router.use("/member/v1/friends", memberFriendRoute);
router.use("/member/v1/post-reactions", memberPostReactionRoute);
router.use("/member/v1/conversations", memberConversationRoute);
router.use("/member/v1/messages", memberMessageRoute);
router.use("/member/v1/members", memberMember);    
router.use("/member/v1/blocks", memberBlockRoute);
router.use("/member/v1/meals", memberMealRoute);
router.use("/member/v1/meal-trackers", memberMealTrackerRoute);
router.use("/member/v1/water-trackers", memberWaterTrackerRoute);
router.use("/member/v1", systemParameterRoute);
router.use("/member/v1/report-category", memberReportCategoryRoute);
router.use("/member/v1/post-report", memberPostReportRoute);
router.use("/member/v1", memberPostViewsRoute);
router.use("/member/v1", planDurationRoute);
router.use("/member/v1", memberPlanListRoute);
router.use("/member/v1", memberTypeLevelRoute);

export default router;
