-- AlterTable
ALTER TABLE `BadHabit` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `BankInformation` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `BodyAttentionArea` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `BodyGoal` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Category` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Cons` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `DietType` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Meal` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `MealType` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Member` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `MemberPlan` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `MemberType` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Permission` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `PhysicalLimitation` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Place` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `ProficientLevel` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Pros` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Role` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Shop` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `ShopLevel` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Tag` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `deletedAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `Workout` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DELETE') NOT NULL DEFAULT 'ACTIVE';
